// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcjT83c7PjwXGWszYI9f-B6nNDfuTk7Ds',
    appId: '1:333513427564:android:60cfc29f2e30967561e649',
    messagingSenderId: '333513427564',
    projectId: 'slsalt-6ea65',
    authDomain: 'slsalt-6ea65.firebaseapp.com',
    storageBucket: 'slsalt-6ea65.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcjT83c7PjwXGWszYI9f-B6nNDfuTk7Ds',
    appId: '1:333513427564:android:60cfc29f2e30967561e649',
    messagingSenderId: '333513427564',
    projectId: 'slsalt-6ea65',
    storageBucket: 'slsalt-6ea65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcjT83c7PjwXGWszYI9f-B6nNDfuTk7Ds',
    appId: '1:333513427564:android:60cfc29f2e30967561e649',
    messagingSenderId: '333513427564',
    projectId: 'slsalt-6ea65',
    storageBucket: 'slsalt-6ea65.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcjT83c7PjwXGWszYI9f-B6nNDfuTk7Ds',
    appId: '1:333513427564:android:60cfc29f2e30967561e649',
    messagingSenderId: '333513427564',
    projectId: 'slsalt-6ea65',
    storageBucket: 'slsalt-6ea65.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcjT83c7PjwXGWszYI9f-B6nNDfuTk7Ds',
    appId: '1:333513427564:android:60cfc29f2e30967561e649',
    messagingSenderId: '333513427564',
    projectId: 'slsalt-6ea65',
    authDomain: 'slsalt-6ea65.firebaseapp.com',
    storageBucket: 'slsalt-6ea65.appspot.com',
  );
}
